version: "3.9"

services:
  
  database:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: FamPay_db
      POSTGRES_PASSWORD: postgres

  web:
    build: sohamk21/fampay_backend:latest
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - database

volumes:
  pg_data:
    