# Generated by Django 4.0.5 on 2022-06-21 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='snippet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='Youtube.snippet'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='Youtube.videolist'),
        ),
    ]
